// <auto-generated />
using System;
using Abac.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abac.WebApi.Migrations.Casbin
{
    [DbContext(typeof(LocalCasbinDbContext))]
    [Migration("20260320212858_initCasbin")]
    partial class initCasbin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Casbin.Persist.Adapter.EFCore.Entities.EFCorePersistPolicy<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ptype");

                    b.Property<string>("Value1")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v0");

                    b.Property<string>("Value10")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v9");

                    b.Property<string>("Value11")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v10");

                    b.Property<string>("Value12")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v11");

                    b.Property<string>("Value13")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v12");

                    b.Property<string>("Value14")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v13");

                    b.Property<string>("Value2")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v1");

                    b.Property<string>("Value3")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v2");

                    b.Property<string>("Value4")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v3");

                    b.Property<string>("Value5")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v4");

                    b.Property<string>("Value6")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("v5");

                    b.Property<string>("Value7")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v6");

                    b.Property<string>("Value8")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v7");

                    b.Property<string>("Value9")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("v8");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Value1");

                    b.HasIndex("Value2");

                    b.HasIndex("Value3");

                    b.HasIndex("Value4");

                    b.HasIndex("Value5");

                    b.HasIndex("Value6");

                    b.ToTable("casbin_rule", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
